/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package volume_01;

import java.awt.CardLayout;
import java.awt.Dimension;
import javax.swing.JPopupMenu;
import javax.swing.ToolTipManager;

/**
 *
 * @author IMG_1
 */
public class Frame1 extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    cube mainCube = new cube();

    public Frame1() {
        initComponents();
        try {
            javax.swing.SwingUtilities.invokeLater(new Runnable() {
                public void run() {
                    MainCylinder mainCylinder = new MainCylinder();
                    jPanel1.add(mainCube);
                    jPanel2.add(mainCylinder);
                    jPanel3.add(new MainCone());
                    jPanel4.add(new MainSphere());
                }
            });
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        ma_ca = new javax.swing.JPanel();
        set1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        set2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        set3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        set4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        value_cube = new javax.swing.JLabel();
        showPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel6.setLayout(new java.awt.GridLayout(1, 2));

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Setting"));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cube", "Cylinder", "Cone", "Sphere" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel12.add(jComboBox1);

        ma_ca.setPreferredSize(new java.awt.Dimension(300, 50));
        ma_ca.setLayout(new java.awt.CardLayout());

        jLabel5.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        jLabel5.setText("กว้าง");

        jLabel1.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        jLabel1.setText("ยาว");

        jLabel6.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        jLabel6.setText("สูง");

        jTextField1.setText("10");

        jTextField2.setText("10");

        jTextField3.setText("10");

        jButton1.setText("Set");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout set1Layout = new javax.swing.GroupLayout(set1);
        set1.setLayout(set1Layout);
        set1Layout.setHorizontalGroup(
            set1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(set1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        set1Layout.setVerticalGroup(
            set1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(set1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(set1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(set1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addGroup(set1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel1)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        ma_ca.add(set1, "Cube");

        jLabel2.setText("jLabel2");
        set2.add(jLabel2);

        ma_ca.add(set2, "Cylinder");

        jLabel3.setText("jLabel3");
        set3.add(jLabel3);

        ma_ca.add(set3, "Cone");

        jLabel4.setText("jLabel4");
        set4.add(jLabel4);

        ma_ca.add(set4, "Sphere");

        jPanel12.add(ma_ca);

        jPanel6.add(jPanel12);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jLabel7.setText("Volume = ");
        jLabel7.setToolTipText("");
        jPanel7.add(jLabel7);

        value_cube.setText(String.format("%.2f", this.mainCube.tosetSize())

        );
        jPanel7.add(value_cube);

        jPanel6.add(jPanel7);

        getContentPane().add(jPanel6, java.awt.BorderLayout.SOUTH);

        showPanel.setLayout(new java.awt.CardLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(200, 200));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 200));
        showPanel.add(jPanel1, "Cube");
        showPanel.add(jPanel2, "Cylinder");

        jPanel3.setPreferredSize(new java.awt.Dimension(0, 0));
        showPanel.add(jPanel3, "Cone");

        jPanel4.setPreferredSize(new Dimension(500, 500));
        showPanel.add(jPanel4, "Sphere");

        getContentPane().add(showPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged

        CardLayout cardShow = (CardLayout) showPanel.getLayout();
        cardShow.show(showPanel, (String) jComboBox1.getSelectedItem());

        CardLayout cardSet = (CardLayout) ma_ca.getLayout();
        cardSet.show(ma_ca, (String) jComboBox1.getSelectedItem());

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.mainCube.tosetSize(Float.parseFloat(jTextField1.getText()),Float.parseFloat(jTextField2.getText()),Float.parseFloat(jTextField3.getText()));
        this.value_cube.setText(String.format("%.2f", this.mainCube.tosetSize()));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel ma_ca;
    private javax.swing.JPanel set1;
    private javax.swing.JPanel set2;
    private javax.swing.JPanel set3;
    private javax.swing.JPanel set4;
    private javax.swing.JPanel showPanel;
    private javax.swing.JLabel value_cube;
    // End of variables declaration//GEN-END:variables
}
