/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package volume_01;

import java.awt.CardLayout;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.ToolTipManager;

/**
 *
 * @author IMG_1
 */
public class volume_01 extends javax.swing.JFrame {

    /**
     * Creates new form volume_01
     */
    Cube mainCube = new Cube();
    Cylinder mainCylinder = new Cylinder();
    Cone mainCone = new Cone();
    Sphere mainSphere = new Sphere();

    public volume_01() {
        initComponents();
        try {
            javax.swing.SwingUtilities.invokeLater(new Runnable() {
                public void run() {

                    jPanel1.add(mainCube);
                    jPanel2.add(mainCylinder);
                    jPanel3.add(mainCone);
                    jPanel4.add(mainSphere);
                }
            });
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        ma_ca = new javax.swing.JPanel();
        set1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        set2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cyR = new javax.swing.JTextField();
        cyH = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        set3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        coR = new javax.swing.JTextField();
        coH = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        set4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        spR = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        value_volume = new javax.swing.JLabel();
        showPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel6.setLayout(new java.awt.GridLayout(1, 2));

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Setting"));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cube", "Cylinder", "Cone", "Sphere" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel12.add(jComboBox1);

        ma_ca.setPreferredSize(new java.awt.Dimension(300, 50));
        ma_ca.setLayout(new java.awt.CardLayout());

        jLabel5.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        jLabel5.setText("กว้าง");

        jLabel1.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        jLabel1.setText("ยาว");

        jLabel6.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        jLabel6.setText("สูง");

        jTextField1.setText("10");

        jTextField2.setText("10");

        jTextField3.setText("10");

        jButton1.setText("Set");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout set1Layout = new javax.swing.GroupLayout(set1);
        set1.setLayout(set1Layout);
        set1Layout.setHorizontalGroup(
            set1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(set1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        set1Layout.setVerticalGroup(
            set1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(set1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(set1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(set1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addGroup(set1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel1)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        ma_ca.add(set1, "Cube");

        jLabel8.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        jLabel8.setText("รัศมี");

        jLabel10.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        jLabel10.setText("สูง");

        cyR.setText("5");

        cyH.setText("10");

        jButton2.setText("Set");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout set2Layout = new javax.swing.GroupLayout(set2);
        set2.setLayout(set2Layout);
        set2Layout.setHorizontalGroup(
            set2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(set2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cyR, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cyH, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        set2Layout.setVerticalGroup(
            set2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(set2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(set2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(set2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(cyH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(set2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(cyR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2))
                .addGap(20, 20, 20))
        );

        ma_ca.add(set2, "Cylinder");

        jLabel9.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        jLabel9.setText("รัศมี");

        jLabel11.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        jLabel11.setText("สูง");

        coR.setText("4");

        coH.setText("10");

        jButton3.setText("Set");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout set3Layout = new javax.swing.GroupLayout(set3);
        set3.setLayout(set3Layout);
        set3Layout.setHorizontalGroup(
            set3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(set3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coR, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coH, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        set3Layout.setVerticalGroup(
            set3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(set3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(set3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel9)
                    .addComponent(coR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(coH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        ma_ca.add(set3, "Cone");

        jLabel12.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        jLabel12.setText("รัศมี");

        spR.setText("10");

        jButton4.setText("Set");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout set4Layout = new javax.swing.GroupLayout(set4);
        set4.setLayout(set4Layout);
        set4Layout.setHorizontalGroup(
            set4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(set4Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spR, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jButton4)
                .addContainerGap())
        );
        set4Layout.setVerticalGroup(
            set4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(set4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(set4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jLabel12)
                    .addComponent(spR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        ma_ca.add(set4, "Sphere");

        jPanel12.add(ma_ca);

        jPanel6.add(jPanel12);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jLabel7.setText("Volume = ");
        jLabel7.setToolTipText("");
        jPanel7.add(jLabel7);

        value_volume.setText(String.format("%.2f", this.mainCube.tosetSize())

        );
        jPanel7.add(value_volume);

        jPanel6.add(jPanel7);

        getContentPane().add(jPanel6, java.awt.BorderLayout.SOUTH);

        showPanel.setLayout(new java.awt.CardLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(200, 200));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 200));
        showPanel.add(jPanel1, "Cube");
        showPanel.add(jPanel2, "Cylinder");

        jPanel3.setPreferredSize(new java.awt.Dimension(0, 0));
        showPanel.add(jPanel3, "Cone");

        jPanel4.setPreferredSize(new Dimension(500, 500));
        showPanel.add(jPanel4, "Sphere");

        getContentPane().add(showPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged

        CardLayout cardShow = (CardLayout) showPanel.getLayout();
        cardShow.show(showPanel, (String) jComboBox1.getSelectedItem());

        CardLayout cardSet = (CardLayout) ma_ca.getLayout();
        cardSet.show(ma_ca, (String) jComboBox1.getSelectedItem());

        if (jComboBox1.getSelectedIndex() == 0) {
            this.value_volume.setText(String.format("%.2f", this.mainCube.tosetSize()));
        } else if (jComboBox1.getSelectedIndex() == 1) {
            this.value_volume.setText(String.format("%.2f", this.mainCylinder.tosetSize()));
        } else if (jComboBox1.getSelectedIndex() == 2) {
            this.value_volume.setText(String.format("%.2f", this.mainCone.tosetSize()));
        } else if (jComboBox1.getSelectedIndex() == 3) {
            this.value_volume.setText(String.format("%.2f", this.mainSphere.tosetSize()));
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.mainCube.tosetSize(Float.parseFloat(jTextField1.getText()), Float.parseFloat(jTextField2.getText()), Float.parseFloat(jTextField3.getText()));
        this.value_volume.setText(String.format("%.2f", this.mainCube.tosetSize()));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.mainCylinder.tosetSize(Float.parseFloat(cyR.getText()), Float.parseFloat(cyH.getText()));
        this.value_volume.setText(String.format("%.2f", this.mainCylinder.tosetSize()));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.mainCone.tosetSize(Float.parseFloat(coR.getText()), Float.parseFloat(coH.getText()));
        this.value_volume.setText(String.format("%.2f", this.mainCone.tosetSize()));
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.mainSphere.tosetSize(Float.parseFloat(spR.getText()));
        this.value_volume.setText(String.format("%.2f", this.mainSphere.tosetSize()));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(volume_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(volume_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(volume_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(volume_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                volume_01 mainFrame = new volume_01();
                mainFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                mainFrame.pack();
                mainFrame.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField coH;
    private javax.swing.JTextField coR;
    private javax.swing.JTextField cyH;
    private javax.swing.JTextField cyR;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel ma_ca;
    private javax.swing.JPanel set1;
    private javax.swing.JPanel set2;
    private javax.swing.JPanel set3;
    private javax.swing.JPanel set4;
    private javax.swing.JPanel showPanel;
    private javax.swing.JTextField spR;
    private javax.swing.JLabel value_volume;
    // End of variables declaration//GEN-END:variables
}
