/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package volume_02;

import java.awt.Dimension;
import javax.swing.JFrame;
import static volume_02.Source_01.Actor_01;
import static volume_02.Source_02.Actor_02;
import vtk.vtkCamera;
import vtk.vtkInteractorStyleTrackballCamera;
import vtk.vtkProp;
import vtk.vtkRenderWindowPanel;

/**
 *
 * @author IMG_1
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public static vtkRenderWindowPanel renderWindowPanel;
    public Main() {
        initComponents();
        new Source_01();
        new Source_02();
        renderWindowPanel = new vtkRenderWindowPanel();
        renderWindowPanel.setPreferredSize(new Dimension(800, 500));
        renderWindowPanel.setInteractorStyle(new vtkInteractorStyleTrackballCamera());
        renderWindowPanel.GetRenderer().AddActor(Actor_01);
        renderWindowPanel.GetRenderer().AddActor(Actor_02);
        this.Render.add(renderWindowPanel);
        renderWindowPanel.repaint();
        
//        add(new dataSource());
//        add(new cube01());
//        add(new test01());
//        add(new test02());
//        add(new test03());
//        add(new show_bone());
//        add(new test_pick());

//        add(new obj123_test());
//        add(new obj123_show());
//        add(new obj123_show2());
//        add(new obj123_test2());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Render = new javax.swing.JPanel();
        Setting = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 800));

        Render.setPreferredSize(new java.awt.Dimension(8, 100));
        Render.setLayout(new java.awt.GridLayout());
        getContentPane().add(Render, java.awt.BorderLayout.CENTER);

        Setting.setBorder(javax.swing.BorderFactory.createTitledBorder("Setting"));
        Setting.setPreferredSize(new Dimension(100,100));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Setting.add(jButton1);

        getContentPane().add(Setting, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        renderWindowPanel.GetRenderer().RemoveAllViewProps();
        renderWindowPanel.resetCamera();
        renderWindowPanel.repaint();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                Main main = new Main();
                main.setVisible(true);
                main.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                main.pack();
                main.setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Render;
    private javax.swing.JPanel Setting;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
