/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package volume_02;

import java.awt.CardLayout;
import java.awt.Dimension;
import javax.swing.JFrame;
import static volume_02.Source_01.Actor_01;
import static volume_02.Source_02.Actor_02;
import static volume_02.Source_03.Actor_03;
import static volume_02.Source_04.Actor_04;
import static volume_02.Source_05.Actor_05;
import static volume_02.Source_06.Actor_06;
import vtk.vtkCamera;
import vtk.vtkInteractorStyleTrackballCamera;
import vtk.vtkProp;
import vtk.vtkRenderWindowPanel;

/**
 *
 * @author IMG_1
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public static vtkRenderWindowPanel renderWindowPanel;

    public Main() {
        initComponents();
        new Source_01();
        new Source_02();
        new Source_03();
        new Source_04();
        new Source_05();
        new Source_06();

        renderWindowPanel = new vtkRenderWindowPanel();
        renderWindowPanel.setPreferredSize(new Dimension(800, 500));
        renderWindowPanel.setInteractorStyle(new vtkInteractorStyleTrackballCamera());
        renderWindowPanel.GetRenderer().AddActor(Actor_01);
        this.Render.add(renderWindowPanel);
        renderWindowPanel.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Render = new javax.swing.JPanel();
        Setting = new javax.swing.JPanel();
        Setting_panel = new javax.swing.JPanel();
        select_source = new javax.swing.JComboBox();
        Output_panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Render.setMinimumSize(new java.awt.Dimension(800, 600));
        Render.setPreferredSize(new java.awt.Dimension(800, 600));
        Render.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(Render, java.awt.BorderLayout.CENTER);

        Setting.setPreferredSize(new java.awt.Dimension(800, 100));
        Setting.setLayout(new java.awt.GridLayout(1, 2));

        Setting_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Setting"));

        select_source.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "สี่เหลี่ยม", "ทรงสี่เหลี่ยมมุมฉาก", "ทรงลูกบาศ์ก", "วงกลม", "ทรงกระบอก1", "ทรงกระบอก2" }));
        select_source.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                select_sourceItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout Setting_panelLayout = new javax.swing.GroupLayout(Setting_panel);
        Setting_panel.setLayout(Setting_panelLayout);
        Setting_panelLayout.setHorizontalGroup(
            Setting_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Setting_panelLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(select_source, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        Setting_panelLayout.setVerticalGroup(
            Setting_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Setting_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(select_source, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        Setting.add(Setting_panel);

        Output_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));
        Setting.add(Output_panel);

        getContentPane().add(Setting, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void select_sourceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_select_sourceItemStateChanged
        if (this.select_source.getSelectedIndex() == 0) {
            renderWindowPanel.GetRenderer().RemoveAllViewProps();
            renderWindowPanel.GetRenderer().AddActor(Actor_01);
            renderWindowPanel.resetCamera();
            renderWindowPanel.repaint();
        }else if (this.select_source.getSelectedIndex() == 1) {
            renderWindowPanel.GetRenderer().RemoveAllViewProps();
            renderWindowPanel.GetRenderer().AddActor(Actor_02);
            renderWindowPanel.resetCamera();
            renderWindowPanel.repaint();
        }else if (this.select_source.getSelectedIndex() == 2) {
            renderWindowPanel.GetRenderer().RemoveAllViewProps();
            renderWindowPanel.GetRenderer().AddActor(Actor_03);
            renderWindowPanel.resetCamera();
            renderWindowPanel.repaint();
        }else if (this.select_source.getSelectedIndex() == 3) {
            renderWindowPanel.GetRenderer().RemoveAllViewProps();
            renderWindowPanel.GetRenderer().AddActor(Actor_04);
            renderWindowPanel.resetCamera();
            renderWindowPanel.repaint();
        }else if (this.select_source.getSelectedIndex() == 4) {
            renderWindowPanel.GetRenderer().RemoveAllViewProps();
            renderWindowPanel.GetRenderer().AddActor(Actor_05);
            renderWindowPanel.resetCamera();
            renderWindowPanel.repaint();
        }else if (this.select_source.getSelectedIndex() == 5) {
            renderWindowPanel.GetRenderer().RemoveAllViewProps();
            renderWindowPanel.GetRenderer().AddActor(Actor_06);
            renderWindowPanel.resetCamera();
            renderWindowPanel.repaint();
        }

// TODO add your handling code here:
    }//GEN-LAST:event_select_sourceItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                Main main = new Main();
                main.setVisible(true);
                main.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                main.pack();
                main.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Output_panel;
    private javax.swing.JPanel Render;
    private javax.swing.JPanel Setting;
    private javax.swing.JPanel Setting_panel;
    private javax.swing.JComboBox select_source;
    // End of variables declaration//GEN-END:variables
}
