/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package volume_ct;

import java.awt.Dimension;
import static java.lang.Math.abs;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import vtk.vtkActor;
import vtk.vtkImageData;
//import vtk.vtkImageSlice;
import vtk.vtkInteractorStyleTrackballCamera;
import vtk.vtkRenderWindowPanel;

/**
 *
 * @author IMG_1
 */
public class Main extends javax.swing.JFrame {

    static {
        System.loadLibrary("vtkCommonJava");
        System.loadLibrary("vtkFilteringJava");
        System.loadLibrary("vtkIOJava");
        System.loadLibrary("vtkImagingJava");
        System.loadLibrary("vtkGraphicsJava");
        System.loadLibrary("vtkRenderingJava");
    }

    /**
     * Creates new form Main
     */
    private static vtkRenderWindowPanel renderWindowPanel;
    private static vtkActor mainActor;
    private static int s1, s2, s3, sgray;
    private static Source source;

    public Main() {

        initComponents();

        mainActor = new vtkActor();

        mainActor.GetProperty().SetColor(0, 1, 0);
        renderWindowPanel = new vtkRenderWindowPanel();
        this.jButton2.doClick();
        renderWindowPanel.setPreferredSize(new Dimension(800, 500));
        renderWindowPanel.setInteractorStyle(new vtkInteractorStyleTrackballCamera());
        renderWindowPanel.GetRenderer().AddActor(mainActor);
        this.Render.add(renderWindowPanel);
        renderWindowPanel.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gauss = new javax.swing.ButtonGroup();
        shrink = new javax.swing.ButtonGroup();
        decimate = new javax.swing.ButtonGroup();
        Render = new javax.swing.JPanel();
        Setting = new javax.swing.JPanel();
        Setting_panel = new javax.swing.JPanel();
        select_source = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        gray_value = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        select_source2 = new javax.swing.JComboBox();
        Output_panel = new javax.swing.JPanel();
        Out01 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Render.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Render.setMinimumSize(new java.awt.Dimension(800, 600));
        Render.setPreferredSize(new java.awt.Dimension(800, 600));
        Render.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(Render, java.awt.BorderLayout.CENTER);

        Setting.setPreferredSize(new java.awt.Dimension(800, 190));
        Setting.setLayout(new java.awt.GridLayout(1, 0));

        Setting_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Setting"));
        Setting_panel.setPreferredSize(new java.awt.Dimension(428, 65));
        Setting_panel.setRequestFocusEnabled(false);

        select_source.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.40 mm", "0.25 mm" }));
        select_source.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                select_sourceItemStateChanged(evt);
            }
        });
        select_source.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_sourceActionPerformed(evt);
            }
        });

        jLabel2.setText("ความละเอียด :");

        jLabel38.setText("ค่าสีเทา: ");

        gray_value.setText("1069");
        gray_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gray_valueActionPerformed(evt);
            }
        });

        jButton2.setText("Show");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel42.setText("วัตถุ :");

        select_source2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        select_source2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                select_source2ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout Setting_panelLayout = new javax.swing.GroupLayout(Setting_panel);
        Setting_panel.setLayout(Setting_panelLayout);
        Setting_panelLayout.setHorizontalGroup(
            Setting_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Setting_panelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(Setting_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Setting_panelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(select_source, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(select_source2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(163, Short.MAX_VALUE))
                    .addGroup(Setting_panelLayout.createSequentialGroup()
                        .addGroup(Setting_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addGroup(Setting_panelLayout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gray_value, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(279, Short.MAX_VALUE))))
        );
        Setting_panelLayout.setVerticalGroup(
            Setting_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Setting_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Setting_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(select_source, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel42)
                    .addComponent(select_source2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Setting_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(gray_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        Setting.add(Setting_panel);

        Output_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));
        Output_panel.setPreferredSize(new java.awt.Dimension(856, 100));
        Output_panel.setLayout(new java.awt.GridLayout(1, 0));

        Out01.setPreferredSize(new java.awt.Dimension(844, 50));

        jLabel3.setText("พื้นที่(mm3) :");

        jLabel4.setText("ค่าสีเทา :");

        jLabel5.setText("ค่าที่วัดได้จากโปรแกรม(mm3) : ");

        jLabel6.setText("คลาดเคลื่อน (mm3) :");

        jLabel7.setText("คลาดเคลื่อน  : ");

        jLabel43.setText("ความละเอียด :");

        jLabel44.setText("วัตถุ :");

        jLabel1.setText("?");

        jLabel8.setText("?");

        jLabel9.setText("?");

        jLabel10.setText("?");

        jLabel11.setText("?");

        jLabel12.setText("?");

        jLabel13.setText("?");

        javax.swing.GroupLayout Out01Layout = new javax.swing.GroupLayout(Out01);
        Out01.setLayout(Out01Layout);
        Out01Layout.setHorizontalGroup(
            Out01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Out01Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(Out01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Out01Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(Out01Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(Out01Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(Out01Layout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(Out01Layout.createSequentialGroup()
                        .addComponent(jLabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addGroup(Out01Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))
                    .addGroup(Out01Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        Out01Layout.setVerticalGroup(
            Out01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Out01Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Out01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Out01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Out01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Out01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Out01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Out01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Out01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13))
                .addGap(25, 25, 25))
        );

        Output_panel.add(Out01);

        Setting.add(Output_panel);

        getContentPane().add(Setting, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void select_sourceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_select_sourceItemStateChanged
        if (this.select_source.getSelectedIndex() == 0) {
            if (this.select_source2.getSelectedIndex() == 0) {
                this.gray_value.setText("1069");
            }
            if (this.select_source2.getSelectedIndex() == 1) {
                this.gray_value.setText("1123");
            }
            if (this.select_source2.getSelectedIndex() == 2) {
                this.gray_value.setText("1154");
            }
        } else {
            if (this.select_source2.getSelectedIndex() == 0) {
                this.gray_value.setText("1014");
            }
            if (this.select_source2.getSelectedIndex() == 1) {
                this.gray_value.setText("1091");
            }
            if (this.select_source2.getSelectedIndex() == 2) {
                this.gray_value.setText("1123");
            }
        }
        this.jButton2.doClick();
// TODO add your handling code here:
    }//GEN-LAST:event_select_sourceItemStateChanged

    private void gray_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gray_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gray_valueActionPerformed

    private void select_source2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_select_source2ItemStateChanged
        if (this.select_source.getSelectedIndex() == 0) {
            if (this.select_source2.getSelectedIndex() == 0) {
                this.gray_value.setText("1069");
            }
            if (this.select_source2.getSelectedIndex() == 1) {
                this.gray_value.setText("1123");
            }
            if (this.select_source2.getSelectedIndex() == 2) {
                this.gray_value.setText("1154");
            }
        } else {
            if (this.select_source2.getSelectedIndex() == 0) {
                this.gray_value.setText("1014");
            }
            if (this.select_source2.getSelectedIndex() == 1) {
                this.gray_value.setText("1091");
            }
            if (this.select_source2.getSelectedIndex() == 2) {
                this.gray_value.setText("1123");
            }
        }
        this.jButton2.doClick();
        // TODO add your handling code here:
    }//GEN-LAST:event_select_source2ItemStateChanged

    private void select_sourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_sourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_select_sourceActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        sgray = Integer.parseInt(this.gray_value.getText());
        source = null;
        if (this.select_source.getSelectedIndex() == 0) {
            if (this.select_source2.getSelectedIndex() == 0) {
                source = new Source_01(sgray);
                mainActor.SetMapper(source.getSourceMapper());
            }
            if (this.select_source2.getSelectedIndex() == 1) {
                source = new Source_02(sgray);
                mainActor.SetMapper(source.getSourceMapper());
            }
            if (this.select_source2.getSelectedIndex() == 2) {
                source = new Source_03(sgray);
                mainActor.SetMapper(source.getSourceMapper());
            }
        } else {
            if (this.select_source2.getSelectedIndex() == 0) {
                source = new Source_04(sgray);
                mainActor.SetMapper(source.getSourceMapper());
            }
            if (this.select_source2.getSelectedIndex() == 1) {
                source = new Source_05(sgray);
                mainActor.SetMapper(source.getSourceMapper());
            }
            if (this.select_source2.getSelectedIndex() == 2) {
                source = new Source_06(sgray);
                mainActor.SetMapper(source.getSourceMapper());
            }
        }

        this.jLabel8.setText(this.select_source.getSelectedItem().toString());
        this.jLabel9.setText(this.select_source2.getSelectedItem().toString());
        this.jLabel10.setText(Double.toString(source.getMVolume()));
        this.jLabel11.setText(String.format("%.2f", source.getVolume()));
        this.jLabel12.setText(String.format("%.2f", abs(source.getMVolume() - source.getVolume())));
        this.jLabel13.setText(String.format("%.2f%%", abs(source.getMVolume() - source.getVolume()) / source.getMVolume() * 100));
        this.jLabel1.setText(this.gray_value.getText());
        renderWindowPanel.repaint();
        renderWindowPanel.resetCameraClippingRange();
        renderWindowPanel.resetCamera();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (Exception e) {
                }

                Main main = new Main();
                main.setVisible(true);
                main.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                main.pack();
                main.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Out01;
    private javax.swing.JPanel Output_panel;
    private javax.swing.JPanel Render;
    private javax.swing.JPanel Setting;
    private javax.swing.JPanel Setting_panel;
    private javax.swing.ButtonGroup decimate;
    private javax.swing.ButtonGroup gauss;
    private javax.swing.JTextField gray_value;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox select_source;
    private javax.swing.JComboBox select_source2;
    private javax.swing.ButtonGroup shrink;
    // End of variables declaration//GEN-END:variables
}
